### ISSUE TITLE
Unable to allocate memory: bad allocation

### ISSUE THREAD

**Issue by schmalls** [darrenkopp/SassyStudio2013#7]
I received the error `Unable to allocate memory: bad allocation` for one of my sass files with the 0.1.7 release. Downgrading to 0.1.6 fixed the issue. I found sass/libsass#586 which may be related, but it is closed.

**Comment by darrenkopp** [comment]
Interesting. I haven't run across this problem yet on the latest, so perhaps it's more heavily influenced by the document. There's not much I can do on this end if it's a libsass issue, but I have been considering moving the compilation to sassc which would alleviate the issue if it was a problem that happens over time.

**Comment by schmalls** [comment]
Yeah, I don't know what is causing the issue. I tried commenting out the entire document and uncommenting lines until the problem appeared. It seems to be an import statement causing an issue. I don't know why since the same import statement works without issues in other documents.

**Comment by schmalls** [comment]
This is no longer an issue with the latest releases.
